### PR TITLE
Use std::String instead of char for Key Names

### PR DESCRIPTION
**Pull request by maximus5684**
Most of the LCD screens from CrystalFontz don't have full keyboards and name their keys things like "Escape" or "Left". This change allows the user to enter these as key names when creating key bindings instead of just a single character.

### CODE REVIEW

**Comment by spdawson** [comment]
Hi Joshua,

Thanks for your work on this.

I have no objection to what you are wanting to achieve, but I'm reluctant to merge this pull request as-is, for the following reasons.
1. The pull request appears to have grown to include changes beyond the stated aim of supporting `std::string` for key names
2. The pull request will break existing client code, as it replaces the `operator()(KeyEvent)` with a `keypress(KeyEvent)` method; looking at your commits, I wonder if this was perhaps a mistake...?
3. Related to the previous point, the `std::string KeyEvent` should probably be passed as const reference to avoid unnecessary copying of the string

Would you be happy to submit a smaller pull request, just for the `std::string` key event support? (I'm quite happy to consider the other changes as further pull requests, by the way.)

Cheers,

Simon

**Comment by spdawson** [comment]
Hi again Joshua,

I've pushed some changes that should enable support for std::string as key names; let me know if it works for you.

Cheers,

Simon

**Comment by maximus5684** [comment]
The changes look good. I'll go ahead and close this request in favor of your changes. THANKS!

**Comment by maximus5684** [comment]
Simon,

Would you mind removing the GCC flag for colors? It wasn't implemented until GCC 4.9 and I'm using 4.8.5 (from Ubuntu 12.04 LTS - required for some software I'm using). I figured it was easier to just comment than make the change, push it, request a pull, and have you merge it.

Thanks,

Josh

**Pull request closed without merging**
